name: Update MIT License Year

on:
  schedule:
    - cron: '0 0 1 1 *'  # Runs at 00:00 UTC on January 1st
  workflow_dispatch:  # Allows manual triggering if needed

jobs:
  update-license:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update License Year
        run: |
          YEAR=$(date +'%Y')
          sed -i "s/Copyright (c) [0-9]\{4\} Hydrovolter/Copyright (c) $YEAR Hydrovolter/" LICENSE

      - name: Commit and Push Changes
        run: |
          if git diff --quiet LICENSE; then
            echo "No changes needed."
            exit 0
          fi
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add LICENSE
          git commit -m "Update MIT License year to $YEAR"
          git push
